### ISSUE TITLE
Graph Clipping in Jupyter Notebooks

### ISSUE THREAD

**Issue by Tianmaru** [mert-kurttutan/torchview#23]
Hey, it's me again :D

I hope, this time, my issue is justified: When visualizing large graphs in Jupyter Notebooks, the graph is not displayed directly, although the produced image is correct. The image is clipped at the right and at the bottom. This seems to be an issue with the graphviz size attribute. However, I could have sworn that this issue wasn't there last week.

Example:
![grafik](https://user-images.githubusercontent.com/27966972/204571047-05b525e5-0db2-4ed3-a5bb-9ecb35d7cd1c.png)

**Comment by mert-kurttutan** [comment]
Hi,
No worries any feedback appreciated :)
The problem seems to stem from the way jupyter/vscode renders svg objects. (This also leads to some clipped images in torchviz)

I suggested a temporary solution in colab notebooks (one of the first cells), which is to change rendering format of graphviz with the following line:

```
graphviz.set_jupyter_format('png')
```
Let me know if this works for you.
Note also that this problem does not exists in google colab.

If you want to insist on svg format, you can use `model_graph.resize_graph(x)` function. Here x is the scaling argument. For instance if x is 2 it doubles the size of image.

P.S. (maybe you already know). Try to put text of executable code, instead of images. Because images is less convenient than text, which can be copied and pasted easily to test. I will put some issue template for this.

**Comment by mert-kurttutan** [comment]
Needless to say, if you have solution to set more robust image size parameter, you are welcome to submit PR.
I think most relevant section for this issue is `resize_graph` function inside `computation_graph.py`

**Comment by mert-kurttutan** [comment]
In addition to the above solution, the following resize command also solves the problem (apply right after creating graph)

```Python
model_graph.resize_graph(1.6)
```

I got the following output

![output](https://user-images.githubusercontent.com/88637659/206839817-f4bdf0cc-fa90-4688-bcac-bb8b86c8e0f3.svg)

**Comment by mert-kurttutan** [comment]
I am closing this issue since I tested my solution on various settings You are welcome to reopen it if you are not satisfied with my solution and to explain why it did not
