### ISSUE TITLE
PyTorch 2.0 Support

### ISSUE THREAD

**Issue by zhiqwang** [mert-kurttutan/torchview#62]
Seems that the main dependency of the code is TorchScript, and PyTorch mainly recommends the dynamo solution for their future release 2.0 version, which seems to be a parallel solution like TorchScript, I wonder if this repository will support dynamo exporting?

**Comment by mert-kurttutan** [comment]
For main mechanism of graph construction algorithm is done through `__torch_function__` API and subclassing `torch.Tensor`.
As it is now, it does not use anything from TorchScript.

If you are asking about visualization support for (Torchscript) compiled modules, this is another matter. As of now, I did not test whether it supports compiled modules.

**Comment by zhiqwang** [comment]
Thanks @mert-kurttutan , got it, that's very cools

**Comment by mert-kurttutan** [comment]
I started (slowly) looking at the compatibility of `torch.dynamo` with `torchview` as there were many exciting changes support for data-dependent flow or optional arguments, this seems to be future for tracing (instead of torchscript).

One advantage of using __torch_function__ is that 
1) we dont rely on torchscript (which seems to be replaced by torch dynamo)
2) we are using the actual forward prop. One implication is that you can use `meta` device to draw the graph. This makes it possible to visualize huge models without any memory issues since `meta` device does not occupy memory.
With `meta` as device, you can visualize T5-3b on google colab (without any GPU)

**Comment by zhiqwang** [comment]
It's just that the following line mistakenly made me think were relying on torchscript, and I was wrongly thinking that only torchscript could produce such a good result.

https://github.com/mert-kurttutan/torchview/blob/e27ba652ff0f1ca1ccd078a670f393dfcb173270/torchview/torchview.py#L12
