### ISSUE TITLE
AssertionError: isolated node! hidden-tensor

### ISSUE THREAD

**Issue by turian** [mert-kurttutan/torchview#73]
**Describe the bug**
```
AssertionError: isolated node! hidden-tensor
```
On a particular model below

**To Reproduce**
```
pip install -e 'git+https://github.com/kkoutini/passt_hear21@0.0.17#egg=hear21passt' 
from hear21passt.base import get_basic_model,get_model_passt
import torch
# get the PaSST model wrapper, includes Melspectrogram and the default pre-trained transformer
model = get_basic_model(mode="logits")
print(model.mel) # Extracts mel spectrogram from raw waveforms.

# optional replace the transformer with one that has the required number of classes i.e. 50
model.net = get_model_passt(arch="passt_s_swa_p16_128_ap476",  n_classes=50)
print(model.net) # the transformer network.


# now model contains mel + the transformer pre-trained model ready to be fine tuned.
# It's still expecting input of the shape [batch, seconds*32000] sampling rate is 32k

model.train()

model_graph = draw_graph(
                model,
                input_size=(
                    4,
                    32000 * 10
                ),
                # # Graph left-to-right: https://github.com/mert-kurttutan/torchview/issues/56
                graph_dir="LR",
                depth=3,
                roll=True,
                expand_nested=True,
                # save_graph=True,
                # directory=tempdir,
            )
```

```
    model_graph = draw_graph(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/torchview.py", line 225, in draw_graph
    model_graph.fill_visual_graph()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/computation_graph.py", line 123, in fill_visual_graph
    self.render_nodes()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/computation_graph.py", line 132, in render_nodes
    self.traverse_graph(self.collect_graph, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/computation_graph.py", line 186, in traverse_graph
    self.traverse_graph(action_fn, **new_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/computation_graph.py", line 186, in traverse_graph
    self.traverse_graph(action_fn, **new_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/computation_graph.py", line 186, in traverse_graph
    self.traverse_graph(action_fn, **new_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/computation_graph.py", line 155, in traverse_graph
    action_fn(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/computation_graph.py", line 198, in collect_graph
    self.check_node(cur_node)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchview/computation_graph.py", line 431, in check_node
    assert not node.is_leaf() or not node.is_root(), (
AssertionError: isolated node! hidden-tensor
```

**Expected behavior**

A graph should be produced.

Note that this model works with depth=1

**Comment by mert-kurttutan** [comment]
Hi,
The error is essentially because of the line [here](https://github.com/kkoutini/passt_hear21/blob/3546288da853689e386d63ce4a963c30e383e4c1/hear21passt/models/preprocess.py#L59) where they use `.item()` to get the value inside the tensor. This then leads to the value of tensor being used instead of tensor itself. This means that this tensor is not attached to the rest of network as `torch.Tensor`s would do in a computational graph.

There are two options I see:
- Ignore these tensors
- Keep these tensors

I will also drop the assertion since this is a legitimate use in a pytorch code.

**Comment by mert-kurttutan** [comment]
Just for documentation purposes, the reason it worked for `depth=1` is because when depth these tensors are not even reached since their depth is 2.

**Comment by turian** [comment]
@mert-kurttutan I would be happy with either. If ignore is easier, then perhaps just do ignore and log a warning to the user?

**Comment by mert-kurttutan** [comment]
Actually, these cases are really rare and correspond to very small part of network. For this to happen, there has to be no operation on the tensor whose `item` method being used. I think ignoring them seems reasonable without any message.
For instance,
```
fmin = self.fmin + torch.randint(self.fmin_aug_range, (1,)).item()
```
Tensor is created and right after this, `item` is applied. So only, this tensor creation part will be ignored. Since this type of part does not contain any operation and is crucial, I will ignore and not send any warning

**Comment by turian** [comment]
Sounds great to me.

**Comment by mert-kurttutan** [comment]
Can you try now using the main branch of the repo? After this, I can release the new version.

**Comment by turian** [comment]
@mert-kurttutan I'm traveling right now so I cannot check immediately.

**Comment by turian** [comment]
On SHA 00bd35b9bbb6e21df2613fcc89ce3f4833edf767

it works!

![image](https://user-images.githubusercontent.com/65918/214159312-0023dd5d-04f5-44d3-b77b-a5d51d80a0d5.png)


Thank you!
